### ISSUE TITLE
[Bug] Error on device update - switches work, but not bulbs

### ISSUE THREAD

**Issue by ThumpWump** [JoshuaMulliken/ha-wyzeapi#101]
Looking forward to using this integration with the bulbs. Not having luck trying to resolve the following error message. The switches connect just fine, but the bulbs aren’t being detected. 
Running version: v0.5.12

2020-12-19 02:50:24 DEBUG (MainThread) [custom_components.wyzeapi] Connected to Wyze account
2020-12-19 02:50:24 DEBUG (MainThread) [custom_components.wyzeapi] Starting WyzeApi components
2020-12-19 02:50:24 DEBUG (MainThread) [custom_components.wyzeapi] Starting WyzeApi Lights
2020-12-19 02:50:24 DEBUG (MainThread) [custom_components.wyzeapi] Starting WyzeApi switches
2020-12-19 02:50:24 ERROR (MainThread) [custom_components.wyzeapi] WyzeApi authenticated but could not find any devices.
2020-12-19 02:50:24 DEBUG (MainThread) [custom_components.wyzeapi.light] Creating new WyzeApi light component
2020-12-19 02:50:24 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Running list_bulbs
2020-12-19 02:50:24 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Running get_devices
2020-12-19 02:50:24 DEBUG (MainThread) [custom_components.wyzeapi.switch] Creating new WyzeApi switch component
2020-12-19 02:50:24 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Running list_switches
2020-12-19 02:50:24 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Running get_devices
2020-12-19 02:50:24 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Bedroom Light 2
2020-12-19 02:50:24 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Bedroom Light 2
2020-12-19 02:50:24 DEBUG (MainThread) [custom_components.wyzeapi.light] Updating Light: Bedroom Light 1
2020-12-19 02:50:24 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Bedroom Light 1
2020-12-19 02:50:24 DEBUG (MainThread) [custom_components.wyzeapi.switch] Updating Switch: Plug 2
2020-12-19 02:50:24 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: Plug 2
2020-12-19 02:50:24 DEBUG (MainThread) [custom_components.wyzeapi.switch] Updating Switch: PLUG 1
2020-12-19 02:50:24 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Updating: PLUG 1
2020-12-19 02:50:24 ERROR (MainThread) [homeassistant.components.light] wyzeapi: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
await task
File "/config/custom_components/wyzeapi/light.py", line 160, in async_update
self.__light = await self.__client.update(self.__light)
File "/config/custom_components/wyzeapi/wyzeapi/client.py", line 248, in update
vars(device)[device_prop] = int(value)
ValueError: invalid literal for int() with base 10: ''

**Comment by mzelmanovich** [comment]
I am seeing the same thing for my contact sensors and now they do not use within the wyze app either

**Comment by mzelmanovich** [comment]
Switched back to wyze sense and had no issues. I think this is some sort of rate limit on wyze end.

**Comment by B-Kramer** [comment]
Seeing the same thing:

wyzeapi: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/config/custom_components/wyzeapi/light.py", line 160, in async_update
    self.__light = await self.__client.update(self.__light)
  File "/config/custom_components/wyzeapi/wyzeapi/client.py", line 248, in update
    vars(device)[device_prop] = int(value)
ValueError: invalid literal for int() with base 10: ''

**Comment by mzelmanovich** [comment]
Can either of you still get updates within the wyze app and/or are you seeing odd delays?

**Comment by B-Kramer** [comment]
> Can either of you still get updates within the wyze app and/or are you seeing odd delays?

Seeing some strange delays/desyncs right now.  I'm trying to ignore it and hoping it's on Wyze's side.

**Comment by B-Kramer** [comment]
According to Wyze they are having issues today:
https://wyzelabs.zendesk.com/hc/en-us/articles/360015979872-Service-Status-Known-Issues

**Comment by mzelmanovich** [comment]
Thanks for the heads up. When I was having issues this morning they were
stating they were all clear. Is it just me or is wyze becoming less
reliable? That is not a reflection on this project which is amazing!

Mitchell Zelmanovich
856.254.5687
mzelmanovich@gmail.com
------------------------------

**Comment by JoshuaMulliken** [comment]
@ThumpWump this was an issue with the Wyze servers and not this integration?

**Comment by B-Kramer** [comment]
> @ThumpWump this was an issue with the Wyze servers and not this integration?

Yeah my issues resolved after Wyze servers returned to normal.
