### ISSUE TITLE
Error on Device Update

### ISSUE THREAD

**Issue by tdemelle** [JoshuaMulliken/ha-wyzeapi#102]
Have tried latest and latest beta.  getting error:

Logger: homeassistant.components.light
Source: custom_components/wyzeapi/wyzeapi/client.py:248
Integration: Light (documentation, issues)
First occurred: 3:42:10 PM (1 occurrences)
Last logged: 3:42:10 PM

wyzeapi: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/config/custom_components/wyzeapi/light.py", line 160, in async_update
    self.__light = await self.__client.update(self.__light)
  File "/config/custom_components/wyzeapi/wyzeapi/client.py", line 248, in update
    vars(device)[device_prop] = int(value)
ValueError: invalid literal for int() with base 10: ''

**Comment by JoshuaMulliken** [comment]
Thank you for the information! I will check on that

**Comment by JoshuaMulliken** [comment]
@tdemelle apparently this was an issue with the Wyze servers and not this project is it working currently?

**Comment by tdemelle** [comment]
Thanks for following up.  Yes, it’s working now. Sorry for the false alarm!
