### ISSUE TITLE
[Feature Request] Wyze Color Bulbs

### ISSUE THREAD

**Issue by npeskoe** [JoshuaMulliken/ha-wyzeapi#126]
Wyze app is authenticating properly, but it is not finding bulb. Does this integration work with new color bulbs?

Logger: custom_components.wyzeapi
Source: custom_components/wyzeapi/__init__.py:80
Integration: Wyze Bulb and Switch Api Integration (documentation)
First occurred: 9:38:04 AM (1 occurrences)
Last logged: 9:38:04 AM

WyzeApi authenticated but could not find any devices.

-------------------------------------------------------------------
Wyze Bulb and Switch Home Assistant Integration
Version: v0.5.12
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/JoshuaMulliken/ha-wyzeapi/issues
-------------------------------------------------------------------
2021-03-31 09:37:57 DEBUG (MainThread) [custom_components.wyzeapi] Creating new WyzeApi component
2021-03-31 09:37:57 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Running login
2021-03-31 09:37:57 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Running __create_md5_md5
2021-03-31 09:38:01 WARNING (MainThread) [homeassistant.setup] Setup of zone is taking over 10 seconds.
2021-03-31 09:38:04 DEBUG (MainThread) [custom_components.wyzeapi] Connected to Wyze account
2021-03-31 09:38:04 DEBUG (MainThread) [custom_components.wyzeapi] Starting WyzeApi components
2021-03-31 09:38:04 DEBUG (MainThread) [custom_components.wyzeapi] Starting WyzeApi Lights
2021-03-31 09:38:04 ERROR (MainThread) [custom_components.wyzeapi] WyzeApi authenticated but could not find any devices.
2021-03-31 09:38:04 DEBUG (MainThread) [custom_components.wyzeapi.light] Creating new WyzeApi light component
2021-03-31 09:38:04 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Running list_bulbs
2021-03-31 09:38:04 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.client] Running get_devices

**Comment by JoshuaMulliken** [comment]
It doesn't work with color bulbs yet. Mine are arriving soon and I will be adding support at that point

**Comment by ItsRhen** [comment]
I second! 🙂 Just got mine and this would be great. Thanks a lot.

**Comment by jscherry** [comment]
Mine will arrive soon. Looking forward to getting color bulbs working. Thanks for writing this code guys

**Comment by jscherry** [comment]
There’s a remote control car coming out tomorrow that works with a v2 camera connection

**Comment by SerpentDrago** [comment]
> There’s a remote control car coming out tomorrow that works with a v2 camera connection

you should check the date .......

**Comment by JoshuaMulliken** [comment]
There is a new beta out with support for the color bulbs. Please read the changelog before installing in case it breaks one of your use cases.

Please report any issues you find with the color bulb support

**Comment by jscherry** [comment]
Will the api for the color bulbs work with sensors and locks again soon? Just got my bulbs and would be glad to help any way I can. I'm a newb as far as burp goes but learn fast.

**Comment by JoshuaMulliken** [comment]
@jscherry I do not think that I will be bringing locks or sensors back. Sensors are losing support from wyze fast some information on this reasoning can be found [here](https://github.com/kevinvincent/ha-wyzesense). For the locks, I don't have them and the only functionality currently is the binary sensor, too much effort to continue to maintain.

**Comment by Mattie** [comment]
It did seem to work with the first color bulb I tried. The problem I had is just having a Wyze watch in the account seemed to break it such that I didn't get a working light? Maybe I just wasn't seeing it. But I removed my watch and now I see one of my bulbs for sure.

```
2021-04-03 11:28:01 ERROR (MainThread) [homeassistant.components.switch] Error while setting up wyzeapi platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzeapi/switch.py", line 40, in setup_platform
    if DeviceTypes(device.product_type) == DeviceTypes.PLUG:
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 'Wrist' is not a valid DeviceTypes
2021-04-03 11:28:01 ERROR (MainThread) [homeassistant.components.light] Error while setting up wyzeapi platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzeapi/light.py", line 48, in setup_platform
    if DeviceTypes(device.product_type) == DeviceTypes.LIGHT:
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 'Wrist' is not a valid DeviceTypes
```

Though as I removed that from my Wyze account (don't use it much), my first bulb appeared just fine. Time to add more of them. :) Thanks so much for working on this!

**Comment by aasquith94** [comment]
With the new update the colors bulbs do not show but also my normal bulbs no longer show as well.

**Comment by aasquith94** [comment]
Error while setting up wyzeapi platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzeapi/light.py", line 48, in setup_platform
    if DeviceTypes(device.product_type) == DeviceTypes.LIGHT:
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 'BaseStation' is not a valid DeviceTypes

**Comment by JoshuaMulliken** [comment]
Hey @aasquith94 can you update to the latest beta and let me know if it is working?

**Comment by aasquith94** [comment]
Same issue. Latest being Beta.4 correct? heres the logs incase theyre slightly different:

Logger: homeassistant.components.light
Source: custom_components/wyzeapi/light.py:48 
Integration: Light (documentation, issues) 
First occurred: 7:16:20 PM (1 occurrences) 
Last logged: 7:16:20 PM

Error while setting up wyzeapi platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzeapi/light.py", line 48, in setup_platform
    if DeviceTypes(device.product_type) == DeviceTypes.LIGHT:
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 'BaseStation' is not a valid DeviceTypes




Logger: homeassistant.components.switch
Source: custom_components/wyzeapi/switch.py:40 
Integration: Switch (documentation, issues) 
First occurred: 7:16:20 PM (1 occurrences) 
Last logged: 7:16:20 PM

Error while setting up wyzeapi platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzeapi/switch.py", line 40, in setup_platform
    if DeviceTypes(device.product_type) == DeviceTypes.PLUG:
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 'BaseStation' is not a valid DeviceTypes

**Comment by JoshuaMulliken** [comment]
Ok. Can you try beta.5?

**Comment by WBETHERI** [comment]
Mine will also not start -- looks like having the Wyze Scale on my account is bricking the DeviceTypes() check from wyzeapy.
I'd try and do a PR (just for an error handling stub so it doesn't brick-- I know there's a separate issue for scale support) but that repo's not public! Haha.

My trace:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzeapi/light.py", line 48, in setup_platform
    if DeviceTypes(device.product_type) == DeviceTypes.LIGHT:
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 'WyzeScale' is not a valid DeviceTypes

**Comment by JoshuaMulliken** [comment]
Awesome. I have added WyzeScale!

New beta is available. I know that this is a painful process, but it is helping me build an understanding of all the different devices that exist in the ecosystem.

**Comment by aasquith94** [comment]
Beta 5 worked for me, thanks so much. ill update to beta 6 and test as well

**Comment by WBETHERI** [comment]
Beta 6 and the color bulbs work now (not getting hung up on WyzeScale).

**Comment by JoshuaMulliken** [comment]
That is great! @aasquith94 @WBETHERI 

Thank you for your help with testing!

**Comment by amitvaria** [comment]
In my testing, I am having issues getting automation working. The scene is created, the lights brightness is set, but after 4s the scene doesn't get called again. I also have Lutron switches in the house and if use thos entities, things work as expected.

```
alias: DoorDashArriving
description: ''
trigger:
  - platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: "doordash_arriving"
condition: []
action:
  - service: scene.create
    data:
      scene_id: dd_before
      snapshot_entities: 
        - light.amit_office_1
        - light.amit_office_2
        - light.amit_office_3
  - service: light.turn_on
    data:
      brightness: 150
    target:
      entity_id:
        - light.amit_office_1
        - light.amit_office_2
        - light.amit_office_3
  - delay: 00:00:04
  - service: scene.turn_on
    data:
      entity_id: scene.dd_before
```

**Comment by drguitarum2005** [comment]
Beta 7 still having issues. What is the "common" device type? I have cameras, headphones, and color bulbs on my Wyze account.

**`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzeapi/light.py", line 48, in setup_platform
    if DeviceTypes(device.product_type) == DeviceTypes.LIGHT:
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 'Common' is not a valid DeviceTypes`**

**Comment by amitvaria** [comment]
When I turn on debugging, I see that activating the scene is trying to set both brightness and hs_color:
```
2021-04-05 21:32:35 DEBUG (SyncWorker_10) [custom_components.wyzeapi.light] {'brightness': 1, 'hs_color': (33.333, 14.118)}
2021-04-05 21:32:35 DEBUG (SyncWorker_10) [custom_components.wyzeapi.light] Setting brightness
```
I think my issue comes from [this](https://github.com/JoshuaMulliken/ha-wyzeapi/blob/color_bulbs_support/custom_components/wyzeapi/light.py#L109). Preference is given to brightness and color is skipped.

**Comment by JoshuaMulliken** [comment]
Ok, fixes for both of those issues is in beta 8.1.

Please let me know if it is working now. I working to get this release pulled into master as a new stable release.

**Comment by amitvaria** [comment]
Tested my issue and it's resolved. Thanks!

**Comment by JoshuaMulliken** [comment]
Great!

**Comment by drguitarum2005** [comment]
My issue about 'common' is resolved and I have my 4 bulbs loaded in.

Another small bug: in Wyze app, you can group 2+ bulbs together and they all change colors together. I have 2 of mine paired that way. Through HA, neither one will change colors until I move the slider on BOTH entities.

**Comment by etchings13** [comment]
I am also getting an error trying to set these up:

Error while setting up wyzeapi platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzeapi/light.py", line 48, in setup_platform
    if DeviceTypes(device.product_type) == DeviceTypes.LIGHT:
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 'JA_RO2' is not a valid DeviceTypes

If it helps, the Devices I have in my account are the Wyze Vacuum, Wyze Doorbell, two Cam v2s and one Cam v3. That is in addition to the new 4-pack of color bulbs obviously.

**Comment by amitvaria** [comment]
> My issue about 'common' is resolved and I have my 4 bulbs loaded in.
> 
> Another small bug: in Wyze app, you can group 2+ bulbs together and they all change colors together. I have 2 of mine paired that way. Through HA, neither one will change colors until I move the slider on BOTH entities.

I'm not sure I understand exactly the issue you're seeing, but I manually created similar light_groups in HA like this:
```
light:
  - platform: group
    name: Amit Office Lights
    entities:
      - light.amit_office_1
      - light.amit_office_2
      - light.amit_office_3
  - platform: group
    name: Gym Lights
    entities:
      - light.gym_1
      - light.gym_2
      - light.gym_3
```

**Comment by mullethunter324** [comment]
Getting the following errors. I have removed my Wyze app bulb grouping to reduce complexity.

Switch:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzeapi/switch.py", line 40, in setup_platform
    if DeviceTypes(device.product_type) == DeviceTypes.PLUG:
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 'JA_RO2' is not a valid DeviceTypes

Light:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzeapi/light.py", line 48, in setup_platform
    if DeviceTypes(device.product_type) == DeviceTypes.LIGHT:
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 'JA_RO2' is not a valid DeviceTypes

**Comment by drguitarum2005** [comment]
> > My issue about 'common' is resolved and I have my 4 bulbs loaded in.
> > Another small bug: in Wyze app, you can group 2+ bulbs together and they all change colors together. I have 2 of mine paired that way. Through HA, neither one will change colors until I move the slider on BOTH entities.
> 
> I'm not sure I understand exactly the issue you're seeing, but I manually created similar light_groups in HA like this:
> 
> ```
> light:
>   - platform: group
>     name: Amit Office Lights
>     entities:
>       - light.amit_office_1
>       - light.amit_office_2
>       - light.amit_office_3
>   - platform: group
>     name: Gym Lights
>     entities:
>       - light.gym_1
>       - light.gym_2
>       - light.gym_3
> ```
> 
> Then you can adjust the bulbs like you can in the Wyze app:
> ![image](https://user-images.githubusercontent.com/1093184/113760587-3d8b5100-96cb-11eb-9864-598a58999809.png)

Thats not a bad way to do it. I'll revert to that if I need to. The issue comes up if you do the grouping within the Wyze app, the grouping doesn't automatically load into HA so you try to adjust one light in HA but nothing responds until you've adjusted all the lights in that group in HA to the same settings.

**Comment by aasquith94** [comment]
My main issue is in scenes. If i select a color temp for the bulb for a normal non color light and run the scene it sets the bulb to the last selected color. so if the circle has purple selected for example, and in the scene i move the color temp slider to warm white and hit save its saving as purple.

**Comment by JoshuaMulliken** [comment]
Working on adding "JA_RO2" as a recognized device

**Comment by JoshuaMulliken** [comment]
@mullethunter324 can you test the latest beta.9?

**Comment by mullethunter324** [comment]
> @mullethunter324 can you test the latest beta.9?

Looking good for me now. Switch and bulbs came in. No errors. Going to test with wyze app bulb grouping later.

**Comment by etchings13** [comment]
> I am also getting an error trying to set these up:
> 
> Error while setting up wyzeapi platform for light
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
> await asyncio.shield(task)
> File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
> result = self.fn(*self.args, **self.kwargs)
> File "/config/custom_components/wyzeapi/light.py", line 48, in setup_platform
> if DeviceTypes(device.product_type) == DeviceTypes.LIGHT:
> File "/usr/local/lib/python3.8/enum.py", line 339, in **call**
> return cls.**new**(cls, value)
> File "/usr/local/lib/python3.8/enum.py", line 662, in **new**
> raise ve_exc
> ValueError: 'JA_RO2' is not a valid DeviceTypes
> 
> If it helps, the Devices I have in my account are the Wyze Vacuum, Wyze Doorbell, two Cam v2s and one Cam v3. That is in addition to the new 4-pack of color bulbs obviously.

beta.9 seems to have fixed the issue for me!

**Comment by drguitarum2005** [comment]
If I accidentally do a couple of rapid state changes (off and on), the switch and icon get out of sync and it’ll update after maybe 15 seconds (HA says light is off but it’s really on). Does that have anything to do with this integration?

**Comment by JoshuaMulliken** [comment]
The Wyze service does not reflect the valid state of the device immediately. It takes about 15 seconds for it to be correct.

**Comment by tggman** [comment]
Just added two color bulbs via the Wyze app, updated HAC to 2021.4 and switched to HA-WyzeAPI to 2021.4-beta.10.1. 

Unfortunately WyzeAPI to 2021.4-beta.10.1 is not working for me.  From the error log:

Logger: homeassistant.components.light
Source: custom_components/wyzeapi/light.py:48
Integration: Light (documentation, issues)
First occurred: 4:44:48 PM (1 occurrences)
Last logged: 4:44:48 PM

Error while setting up wyzeapi platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzeapi/light.py", line 48, in setup_platform
    if DeviceTypes(device.product_type) == DeviceTypes.LIGHT:
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 'JA.SC' is not a valid DeviceTypes

Switching back to the stable release brings my non-color lights back.
