### ISSUE TITLE
Lights not showing in HA

### ISSUE THREAD

**Issue by charger68** [JoshuaMulliken/ha-wyzeapi#167]
I have 2 color bulbs.  I get this error:

Error while setting up wyzeapi platform for light
1:30:06 PM – (ERROR) Light

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/wyzeapi/light.py", line 46, in async_setup_entry
    devices = await hass.async_add_executor_job(get_devices)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzeapi/light.py", line 38, in get_devices
    devices = client.get_devices()
  File "/usr/local/lib/python3.8/site-packages/wyzeapy/client.py", line 84, in get_devices
    object_list = self.client.get_object_list()
  File "/usr/local/lib/python3.8/site-packages/wyzeapy/base_client.py", line 217, in get_object_list
    self.check_for_errors(response_json)
  File "/usr/local/lib/python3.8/site-packages/wyzeapy/base_client.py", line 149, in check_for_errors
    raise ParameterError(response_json)
wyzeapy.base_client.ParameterError: {'ts': 1620754200434, 'code': '1001', 'msg': 'ParameterError', 'data': {}}

I also get the same type of errors for switch, binary_sensor and lock

**Comment by JoshuaMulliken** [comment]
Please check that your password is correct and 2fa is disabled.

**Comment by charger68** [comment]
Thank you!

It was 2FA
