### ISSUE TITLE
Switch: AttributeError: 'WyzeApi' attribute issues

### ISSUE THREAD

**Issue by kprestel** [JoshuaMulliken/ha-wyzeapi#18]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 281, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzeapi/switch.py", line 83, in update
    self._switch.update()
  File "/config/custom_components/wyzeapi/wyzeapi/wyzeapi_switch.py", line 73, in update
    "device_model": self._api._device_model,
AttributeError: 'WyzeApi' object has no attribute '_device_model'

Using config from the `README`

**Comment by aeckard87** [comment]
Confirmed issue is happening for me as well, I attempted to update `wyzeapi_switch.py` but inadvertently crashed my hassio in the process. If I get this working I'll submit a PR to you @JoshuaMulliken :) thanks for this awesome work!!

**Comment by JoshuaMulliken** [comment]
@aeckard87 please checkout the master branch! I believe I found the bug

**Comment by kprestel** [comment]
@JoshuaMulliken that code change looks like it will fix it. Can you please make a release so users using HACS can get it?

**Comment by kprestel** [comment]
This fix creates another error:

2019-12-31 15:03:19 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.plug_1 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 281, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzeapi/switch.py", line 83, in update
    self._switch.update()
  File "/config/custom_components/wyzeapi/wyzeapi/wyzeapi_switch.py", line 80, in update
    "access_token": self._access_token
AttributeError: 'WyzeSwitch' object has no attribute '_access_token'

Do you want me to open a new issue? or do you want to reopen this?

**Comment by JoshuaMulliken** [comment]
I'll open it. It should be a simple fix.

**Comment by JoshuaMulliken** [comment]
Check out the master again and let me know @kprestel

**Comment by JoshuaMulliken** [comment]
I've tagged this as v0.3.2-beta.1

**Comment by kprestel** [comment]
logs look clean! Thanks for the quick fixes and the integration. I look forward to using it more.

**Comment by aeckard87** [comment]
Just updated to  v0.3.2-beta.1, looks good thanks so much @JoshuaMulliken :)
