### ISSUE TITLE
[Bug] Lock gets disconnected after a while, resucitates after a manual lock with the keypad

### ISSUE THREAD

**Issue by Rogergonzalez21** [JoshuaMulliken/ha-wyzeapi#191]
**Describe the bug**

I have an integration that locks my door whenever the door gets closed via a door sensor. The integration works great for a few minutes but if I leave the lock locked for ~1 hour, open it manually and close it, the lock doesn't respond.

I'm pretty sure this started happening after the last HomeAssistant/ha-wyzeapi upgrade

**To Reproduce**

1. Leave the lock locked for +1hour
1. Open it manually
2. Call the service `lock.lock` in an automatization

**Expected behavior**
The lock should lock

**System configuration**
System: Bare metal
HA Version: Home Assistant OS 5.13
WyzeApi Version: 2021.05.21

**home-assistant.log**

```
2021-06-08 09:25:25 ERROR (MainThread) [homeassistant.components.automation.close_front_door_lock_if_the_door_is_closed] Close front door lock if the door is closed: Error executing script. Unexpected error for call_service at pos 1: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
six.raise_from(e, None)
File "<string>", line 3, in raise_from
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
httplib_response = conn.getresponse()
File "/usr/local/lib/python3.8/http/client.py", line 1344, in getresponse
response.begin()
File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
version, status, reason = self._read_status()
File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
return self._sock.recv_into(b)
File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
return self.read(nbytes, buffer)
File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
raise value.with_traceback(tb)
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
six.raise_from(e, None)
File "<string>", line 3, in raise_from
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
httplib_response = conn.getresponse()
File "/usr/local/lib/python3.8/http/client.py", line 1344, in getresponse
response.begin()
File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
version, status, reason = self._read_status()
File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
return self._sock.recv_into(b)
File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
return self.read(nbytes, buffer)
File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 368, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 568, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 760, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 103, in async_lock
await self.hass.async_add_executor_job(ft.partial(self.lock, **kwargs))
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/wyzeapi/lock.py", line 78, in lock
self._client.turn_on(self._device)
File "/usr/local/lib/python3.8/site-packages/wyzeapy/client.py", line 115, in turn_on
self.client.lock_control(device, "remoteLock")
File "/usr/local/lib/python3.8/site-packages/wyzeapy/base_client.py", line 360, in lock_control
response_json = self._session.post(url, json=payload).json()
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
return self.request('POST', url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.8/site-packages/cachecontrol/adapter.py", line 53, in send
resp = super(CacheControlAdapter, self).send(request, **kw)
File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by Rogergonzalez21** [comment]
More info: This morning I downgraded ha-wyzeapi to version 2021.5.19.2 and no issues so far.

**Comment by JoshuaMulliken** [comment]
Please download the latest version (2021.06.1) and test if it is still occuring

**Comment by Rogergonzalez21** [comment]
Updated. I Will let you know if it worked in a couple of days. Thank you for the quick fix!

**Comment by Rogergonzalez21** [comment]
I'm sad to announce the lock keeps disconnecting even after the update. I decided to change my lock connection to use Zigbee now, but I might come back to this plugin soon. Thank you for your work! @JoshuaMulliken :smile: this is really an amazing plugin

**Comment by JoshuaMulliken** [comment]
Hmm, that is weird. I do not have a keypad, so there may be some interaction there that I am not aware of... I will keep this open but I don't think there is much I can do without fully replicating your setup.

**Comment by Rogergonzalez21** [comment]
Do you have a lock? I might be open to sending you a keypad in the near future :thinking:

**Comment by Rogergonzalez21** [comment]
I sent you an email to your hey.com address. It's from my personal email server, so if you don't see it check your SPAM folder :+1:

**Comment by JoshuaMulliken** [comment]
Is the lock the only device in your account @Rogergonzalez21?

**Comment by Rogergonzalez21** [comment]
Yes. This is how my Wyze account looks like: 
![photo_2021-06-28_09-49-02](https://user-images.githubusercontent.com/1617177/123638999-2786bb80-d7f6-11eb-8355-0c3428f1b459.jpg)

Like I mentioned, I also have the keypad, but I think it connects directly to the lock via Bluetooth
