### ISSUE TITLE
access token error in v 0.3.1

### ISSUE THREAD

**Issue by basesnow** [JoshuaMulliken/ha-wyzeapi#20]
Hi, still having access token errors in the latest public version. I did a clean install of the integration in HACS. every once and a while when I restart my server, I get the error. here is the debug. Deleting the wyzeconfig.ini and restarting does reconnect me.

also, noticed that HACS says I am on V0.3.1, but debug shows V0.3.1-beta4. Not sure why??

```
2019-12-30 10:35:30 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-12-30 10:35:30 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for apple_tv which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-12-30 10:35:33 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for wyzesense which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-12-30 10:35:39 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for wyzeapi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-12-30 10:35:39 DEBUG (SyncWorker_19) [custom_components.wyzeapi.light] 
-------------------------------------------------------------------
Wyze Bulb and Switch Home Assistant Integration

Version: v0.3.1-beta.4
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/JoshuaMulliken/ha-wyzeapi/issues
-------------------------------------------------------------------
2019-12-30 10:35:40 INFO (SyncWorker_19) [custom_components.wyzeapi.wyzeapi.wyzeapi_request] Recieved AccessTokenError attempting to regenerate the AccessToken
2019-12-30 10:35:41 ERROR (MainThread) [homeassistant.components.plex] Plex server (https://192-168-1-253.bdaf87b0920e4491bbf1c4f35f4dad8a.plex.direct:32400) could not be reached: [HTTPSConnectionPool(host='192-168-1-253.bdaf87b0920e4491bbf1c4f35f4dad8a.plex.direct', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb1dde410>: Failed to establish a new connection: [Errno 113] Host is unreachable'))]
2019-12-30 10:35:41 ERROR (MainThread) [homeassistant.components.light] Error while setting up platform wyzeapi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzeapi/light.py", line 58, in setup_platform
    add_entities(WyzeBulb(light) for light in wyze.list_bulbs())
  File "/config/custom_components/wyzeapi/wyzeapi/wyzeapi.py", line 88, in list_bulbs
    for device in self.get_devices():
  File "/config/custom_components/wyzeapi/wyzeapi/wyzeapi.py", line 80, in get_devices
    data = do_request(url, payload, self)
  File "/config/custom_components/wyzeapi/wyzeapi/wyzeapi_request.py", line 36, in do_request
    return request_helper(url, payload, api)
  File "/config/custom_components/wyzeapi/wyzeapi/wyzeapi_request.py", line 25, in request_helper
    api.initialize()
  File "/config/custom_components/wyzeapi/wyzeapi/wyzeapi.py", line 26, in initialize
    updateConfig(self._device_id, self._access_token)
  File "/config/custom_components/wyzeapi/wyzeapi/wyzeapi_config.py", line 18, in updateConfig
    config.add_section('auth')
  File "/usr/local/lib/python3.7/configparser.py", line 1205, in add_section
    super().add_section(section)
  File "/usr/local/lib/python3.7/configparser.py", line 658, in add_section
    raise DuplicateSectionError(section)
configparser.DuplicateSectionError: Section 'auth' already exists
2019-12-30 10:35:49 WARNING (MainThread) [homeassistant.setup] Setup of ring is taking over 10 seconds.
2019-12-30 10:35:58 ERROR (MainThread) [homeassistant.components.template.switch] Received invalid switch is_on state: . Expected: on, off, true, false
2019-12-30 10:36:05 WARNING (MainThread) [hacs] You have maykar/compact-custom-header installed with HACS this repository has been blacklisted, please consider removing it.
2019-12-30 10:39:56 WARNING (SyncWorker_6) [homeassistant.components.tplink.switch] Could not read state for 192.168.1.229: Communication error
2019-12-30 10:39:56 WARNING (SyncWorker_17) [homeassistant.components.tplink.switch] Could not read state for 192.168.1.244: Communication error
2019-12-30 10:39:56 WARNING (SyncWorker_9) [homeassistant.components.tplink.switch] Could not read state for 192.168.1.242: Communication error
2019-12-30 10:39:56 WARNING (SyncWorker_0) [homeassistant.components.tplink.switch] Could not read state for 192.168.1.248: Communication error
```

**Comment by aeckard87** [comment]
You may want to checkout this recent issue https://github.com/JoshuaMulliken/ha-wyzeapi/issues/3

For me upgrading to beta5 did the trick
