### ISSUE TITLE
[Bug] Wyze App becomes unusable when integration is enabled

### ISSUE THREAD

**Issue by th3jesta** [JoshuaMulliken/ha-wyzeapi#204]
**Device** 
Wyze Thermostat (no other Wyze devices)

**To Reproduce**

1. Add Wyze integration.
2. Adjust temperature, operation, or fan mode from Wyze integration.
3. Open Wyze mobile app, select Thermostat. Notice temperature setting is incorrect; it does not match thermostat or lovelace card; cloud icon on thermostat in app has a cross through it. (see images below log)
4. Tap settings gear.
5. Tapping on Temperature or Schedule causes the app to restart.

**Expected behavior**
App should operate normally in addition to HA.

**Workaround**
1. Disable Wyze integration in HA.
2. Remove thermostat from Wyze App/Account.
3. Reset thermostat.
4. Re-add thermostat to Wyze account.
5. Leave Wyze integration disabled in HA. Don't use it. :(

**Additional details**
This same behavior was occurring on my HA instance on a RPi 3b+. I was hoping the upgrade to a full-fat x86 server would resolve it magically, but sadly, it did not.

**System configuration**
Version | core-2021.6.6
-- | --
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.9
Operating System Family | Linux
Operating System Version | 5.12.12-xanmod1
CPU Architecture | x86_64
Timezone | America/New_York

**home-assistant.log**
```
2021-06-23 21:47:38 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration wyzeapi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-06-23 21:47:38 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hive which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-06-23 21:47:38 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-06-23 21:47:38 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration mail_and_packages which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-06-23 21:47:43 WARNING (MainThread) [homeassistant.config_entries] Config entry 'EPSON XP-440 Series' for ipp integration not ready yet: Invalid response from API: Error occurred while communicating with IPP server.; Retrying in background
2021-06-23 21:47:47 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2021-06-23 21:47:52 DEBUG (MainThread) [custom_components.wyzeapi] Nothing to import from configuration.yaml, loading from Integrations
2021-06-23 21:47:53 DEBUG (MainThread) [custom_components.wyzeapi.light] Creating new WyzeApi light component
2021-06-23 21:47:53 DEBUG (MainThread) [custom_components.wyzeapi.switch] Creating new WyzeApi light component
2021-06-23 21:47:53 DEBUG (MainThread) [custom_components.wyzeapi.binary_sensor] Creating new WyzeApi binary sensor component
2021-06-23 21:47:53 DEBUG (MainThread) [custom_components.wyzeapi.lock] Creating new WyzeApi lock component
2021-06-23 21:47:53 DEBUG (MainThread) [custom_components.wyzeapi.scene] Creating new WyzeApi group component
2021-06-23 21:47:53 DEBUG (MainThread) [custom_components.wyzeapi.climate] Creating new WyzeApi thermostat component
2021-06-23 21:47:53 DEBUG (MainThread) [custom_components.wyzeapi.alarm_control_panel] Creating new WyzeApi Home Monitoring System component
2021-06-23 21:49:45 WARNING (zeroconf-Engine-242) [zeroconf] Choked at offset 0 while unpacking b'\n\xba\x10\x00'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 752, in __init__
    self.read_header()
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 789, in read_header
    ) = self.unpack(b'!6H')
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 776, in unpack
    info = struct.unpack(format_, self.data[self.offset : self.offset + length])
struct.error: unpack requires a buffer of 12 bytes
```
![image](https://user-images.githubusercontent.com/38670315/123190382-71c21280-d46d-11eb-9199-be7ff59f2f88.png)
![image](https://user-images.githubusercontent.com/38670315/123190416-80a8c500-d46d-11eb-99e2-1035f94fb40f.png)

**Comment by JoshuaMulliken** [comment]
Hello @th3jesta I am able to replicate the cloud logo in the app, but it does not appear to effect operation anywhere in my system.

**Comment by JoshuaMulliken** [comment]
It appears to be having an issue unpacking some data???

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 752, in __init__
    self.read_header()
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 789, in read_header
    ) = self.unpack(b'!6H')
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 776, in unpack
    info = struct.unpack(format_, self.data[self.offset : self.offset + length])
struct.error: unpack requires a buffer of 12 bytes
```

This is definitely a situation where I have no idea what is going on... Have you added it to HA again recently to test?

**Comment by th3jesta** [comment]
Hi Joshua, unfortunately I have not. I am traveling for the next couple of
weeks, so I won't be of much use until I'm home again. I'll be happy to try
again and keep digging when I get back. Thanks for your help!

**Comment by JoshuaMulliken** [comment]
@th3jesta please reopen if it is still occurring for you! Thanks for the submission!

**Comment by th3jesta** [comment]
It looks like 2021.7.9 (or one of the other updates since then) has resolved this issue for me!
