### ISSUE TITLE
[Bug] Thermostat not showing up on latest versions (preset parsing issue?)

### ISSUE THREAD

**Issue by tony-fav** [JoshuaMulliken/ha-wyzeapi#207]
**Describe the bug**
Thermostat disappeared on latest version. 

**To Reproduce**
Have thermostat, upgrade wyzeapi using HACS, thermostat doesn't work anymore. Delete integration, reinstall in HACS, reboot HA, enable integration. Thermostat doesn't even show up now. (looking at the log it looks like it can't parse my preset correctly).

**Expected behavior**
Thermostat to show up.

**System configuration**
Running HA 2021.6.6 in VirtualBox with 2021.7.3

**home-assistant.log**
Logger: homeassistant.components.climate
Source: custom_components/wyzeapi/climate.py:303
Integration: Climate (documentation, issues)
First occurred: 9:09:21 PM (1 occurrences)
Last logged: 9:09:21 PM

wyzeapi: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 432, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_device_update
    await task
  File "/config/custom_components/wyzeapi/climate.py", line 303, in async_update
    self._thermostat = await self._thermostat_service.update(self._thermostat)
  File "/usr/local/lib/python3.8/site-packages/wyzeapy/services/thermostat_service.py", line 86, in update
    thermostat.preset = Preset(value)
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: '{"away":{"cool":"75","heat":"60"},"home":{"cool":"68","heat":"63"},"sleep":{"cool":"66","heat":"61"}}' is not a valid Preset

**Comment by JoshuaMulliken** [comment]
@tony-fav I could reproduce and have fixed it in the latest release.

**Comment by tony-fav** [comment]
@JoshuaMulliken thanks!
