### ISSUE TITLE
[Bug] Sensor Info Not Updating

### ISSUE THREAD

**Issue by bjs-pdx** [JoshuaMulliken/ha-wyzeapi#215]
**Describe the bug**
Multiple V1 and V2 sensors (motion and contact) are failing to update in HA.  The data will update (open/closed motion/no motion) when the system is rebooted or the WYZEapi integration is reloaded.  Shortly there after it stops.

**To Reproduce**
On the overview page I have several "glance cards" that list the sensors and status.  If I click on any of them they will say the last activity was 20 hours ago, even though they have been opened/closed within the last hour or two.

**Expected behavior**
Status of the sensors should be updated as they are opened/closed or as motion is detected.

**System configuration**
System: Home Assistant OS 6.1 on Rpi4
HA Version: core-2021.7.0
WyzeApi Version: 2021.7.9

**configuration.yaml**
Partial Listing of configuration.yaml
`
logger:
  default: warning
  logs:
    custom_components.wyzeapi: debug
wyzeapi:
  username: !secret wyze_user
  password: !secret wyze_password
  sensors: true
  light: false
  switch: true
  lock: false`

```yaml
<YOUR CONFIG HERE>
```

**home-assistant.log**

```
<PUT YOUR LOG HERE>
```
`2021-07-08 13:43:19 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration wyzeapi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-08 13:43:19 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration edgeos which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-08 13:43:19 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration wundergroundpws which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-08 13:43:19 ERROR (SyncWorker_2) [homeassistant.loader] The custom integration 'wundergroundpws' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
2021-07-08 13:43:19 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-08 13:43:19 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration remote_homeassistant which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-08 13:43:22 DEBUG (MainThread) [custom_components.wyzeapi] Importing config information for bjs.pdx@gmail.com from configuration.yml
2021-07-08 13:43:22 DEBUG (MainThread) [custom_components.wyzeapi] Found existing config entries
2021-07-08 13:43:22 DEBUG (MainThread) [custom_components.wyzeapi] Updating existing entry
2021-07-08 13:43:29 WARNING (MainThread) [homeassistant.config_entries] Config entry 'RokuEXP' for roku integration not ready yet: Invalid response from API: Error occurred while communicating with device; Retrying in background
2021-07-08 13:43:30 DEBUG (MainThread) [custom_components.wyzeapi.binary_sensor] Creating new WyzeApi binary sensor component
2021-07-08 13:43:30 DEBUG (MainThread) [custom_components.wyzeapi.switch] Creating new WyzeApi light component
2021-07-08 13:43:30 DEBUG (MainThread) [custom_components.wyzeapi.alarm_control_panel] Creating new WyzeApi Home Monitoring System component
2021-07-08 13:43:30 DEBUG (MainThread) [custom_components.wyzeapi.light] Creating new WyzeApi light component
2021-07-08 13:43:30 DEBUG (MainThread) [custom_components.wyzeapi.lock] Creating new WyzeApi lock component
2021-07-08 13:43:30 DEBUG (MainThread) [custom_components.wyzeapi.climate] Creating new WyzeApi thermostat component
2021-07-08 13:43:43 ERROR (MainThread) [denonavr.foundation] No FriendlyName found, using standard name: Denon AVR
2021-07-08 13:43:56 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform denonavr is taking over 10 seconds.
2021-07-08 16:13:43 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.cam3_deck is taking over 10 seconds
2021-07-08 16:16:13 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.wp08_2 is taking over 10 seconds
2021-07-08 18:03:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.kp01 is taking over 10 seconds
2021-07-08 18:31:27 WARNING (SyncWorker_3) [root] Waiting for authorization...
2021-07-08 18:34:55 ERROR (Thread-5) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.9/threading.py", line 892, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.9/site-packages/wyzeapy/services/sensor_service.py", line 59, in update_worker
callback(asyncio.run_coroutine_threadsafe(self.update(sensor), loop).result())
File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 445, in result
return self.__get_result()
File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
raise self._exception
File "/usr/local/lib/python3.9/site-packages/wyzeapy/services/sensor_service.py", line 29, in update
properties = await self._get_device_info(sensor)
File "/usr/local/lib/python3.9/site-packages/wyzeapy/services/base_service.py", line 468, in _get_device_info
response_json = await self._auth_lib.post("https://api.wyzecam.com/app/v2/device/get_device_Info",
File "/usr/local/lib/python3.9/site-packages/wyzeapy/wyze_auth_lib.py", line 117, in post
return await response.json()
File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1097, in json
raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.wyzecam.com/app/v2/device/get_device_Info')
2021-07-08 18:47:50 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 314, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
2021-07-08 18:47:50 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from laptoptoo.cathartes.aura (192.168.5.9). (Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0)
2021-07-08 21:28:44 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.wcb04 is taking over 10 seconds`

**Comment by JoshuaMulliken** [comment]
Well it looks like we found another exception that can cause them to stop updating. I can fix this later today

**Comment by bjs-pdx** [comment]
Just checked this morning and sensors have stopped updating again.  Using 2021.7.10 version of the api.  Do you want logs?

**Comment by JoshuaMulliken** [comment]
Yes please create a new issue
