### ISSUE TITLE
[Bug] No Devices Found

### ISSUE THREAD

**Issue by defimix** [JoshuaMulliken/ha-wyzeapi#227]
**Describe the bug**
Wyze Integration Installs, but does not return with a list of devices or entities.

**To Reproduce**

In configuration, under integrations... Wyze Home Assistant Integration is listed with no devices or entities listed. This last worked correctly under version 2021.06.2.

**Expected behavior**
Wyze Integration should acknowledge devices and make them available.

**System configuration**
System: Ubuntu Docker; Python v 3.8.7
HA Version: 2021.3.3 (:latest on 8/3/21)
WyzeApi Version: 2021.7.12

**home-assistant.log**
```
2021-08-03 11:45:45 WARNING (MainThread) [homeassistant.loader] You are using a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-08-03 11:45:45 WARNING (MainThread) [homeassistant.loader] You are using a custom integration wyzeapi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-08-03 11:45:46 DEBUG (MainThread) [custom_components.wyzeapi] Nothing to import from configuration.yaml, loading from Integrations
2021-08-03 11:45:47 DEBUG (MainThread) [wyzeapy] Email: xx
2021-08-03 11:45:47 DEBUG (MainThread) [wyzeapy] Password: xx
2021-08-03 11:45:47 DEBUG (MainThread) [wyzeapy.wyze_auth_lib] Request:
2021-08-03 11:45:47 DEBUG (MainThread) [wyzeapy.wyze_auth_lib] url: https://auth-prod.api.wyze.com/user/login
2021-08-03 11:45:47 DEBUG (MainThread) [wyzeapy.wyze_auth_lib] json: {'email': 'xx', 'password': 'xx'}
2021-08-03 11:45:47 DEBUG (MainThread) [wyzeapy.wyze_auth_lib] headers: {'X-API-Key': 'xx'}
2021-08-03 11:45:47 DEBUG (MainThread) [wyzeapy.wyze_auth_lib] data: None
2021-08-03 11:45:49 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Wyze for wyzeapi
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/wyzeapi/__init__.py", line 85, in async_setup_entry
hass.create_task(hass.config_entries.async_forward_entry_setup(config_entry, platform))
AttributeError: 'HomeAssistant' object has no attribute 'create_task'
2021-08-03 11:49:16 DEBUG (MainThread) [wyzeapy] Email: xx
2021-08-03 11:49:16 DEBUG (MainThread) [wyzeapy] Password: xx
2021-08-03 11:49:16 DEBUG (MainThread) [wyzeapy.wyze_auth_lib] Request:
2021-08-03 11:49:16 DEBUG (MainThread) [wyzeapy.wyze_auth_lib] url: https://auth-prod.api.wyze.com/user/login
2021-08-03 11:49:16 DEBUG (MainThread) [wyzeapy.wyze_auth_lib] json: {'email': 'xx', 'password': 'xx'}
2021-08-03 11:49:16 DEBUG (MainThread) [wyzeapy.wyze_auth_lib] headers: {'X-API-Key': 'xx'}
2021-08-03 11:49:16 DEBUG (MainThread) [wyzeapy.wyze_auth_lib] data: None
2021-08-03 11:49:16 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2021-08-03 11:49:16 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector
2021-08-03 11:49:16 DEBUG (MainThread) [wyzeapy] Email: xx
2021-08-03 11:49:16 DEBUG (MainThread) [wyzeapy] Password: xx
2021-08-03 11:49:16 DEBUG (MainThread) [wyzeapy.wyze_auth_lib] Request:
2021-08-03 11:49:16 DEBUG (MainThread) [wyzeapy.wyze_auth_lib] url: https://auth-prod.api.wyze.com/user/login
2021-08-03 11:49:16 DEBUG (MainThread) [wyzeapy.wyze_auth_lib] json: {'email': 'xx', 'password': 'xx'}
2021-08-03 11:49:16 DEBUG (MainThread) [wyzeapy.wyze_auth_lib] headers: {'X-API-Key': 'xx'}
2021-08-03 11:49:16 DEBUG (MainThread) [wyzeapy.wyze_auth_lib] data: None
2021-08-03 11:49:16 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Wyze for wyzeapi
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/wyzeapi/__init__.py", line 85, in async_setup_entry
hass.create_task(hass.config_entries.async_forward_entry_setup(config_entry, platform))
AttributeError: 'HomeAssistant' object has no attribute 'create_task'
2021-08-03 12:00:01 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
```

**Comment by JoshuaMulliken** [comment]
Please update HA
