### ISSUE TITLE
Lost keypad battery info

### ISSUE THREAD

**Issue by jscherry** [JoshuaMulliken/ha-wyzeapi#306]
Running the newest ha beta and updated to wyzeapi version 0.1.0-b4+20211210 and lost lock keypad battery? I also tried downloading master version from hacs but same problem. Where'd the enitity go? It still shows up under lock attrubutes.

```
<PUT YOUR LOG HERE>
```Logger: homeassistant.util.logging
Source: util/logging.py:105
First occurred: 9:09:59 PM (549 occurrences)
Last logged: 10:32:53 PM

Exception in handle_lock_update when dispatching 'wyzeapi.lock_updated-YD.LO1.23e3cde4a379528d7d2f310b221dd4a6': (<Device: DeviceTypes.LOCK, YD.LO1.23e3cde4a379528d7d2f310b221dd4a6>,) Traceback (most recent call last): File "/config/custom_components/wyzeapi/sensor.py", line 86, in handle_lock_update if self.enabled is False | self.enabled is None: TypeError: unsupported operand type(s) for |: 'bool' and 'NoneType'
Exception in handle_lock_update when dispatching 'wyzeapi.lock_updated-YD.LO1.6a4739411019da2d1caea8a133a23758': (<Device: DeviceTypes.LOCK, YD.LO1.6a4739411019da2d1caea8a133a23758>,) Traceback (most recent call last): File "/config/custom_components/wyzeapi/sensor.py", line 86, in handle_lock_update if self.enabled is False | self.enabled is None: TypeError: unsupported operand type(s) for |: 'bool' and 'NoneType'

**Comment by jscherry** [comment]
fixed template sensor for keypads and can see battery status but still seeing error in logs

**Comment by jscherry** [comment]
Camer sirens also gone?

**Comment by JoshuaMulliken** [comment]
@jscherry the old beta had issues so it was pulled. This beta is testing different features.

We will get those features back into testing once all the kinks are ironed out

**Comment by jscherry** [comment]
Great thanks
