### ISSUE TITLE
Python Exception: TypeError When Attempting to handle_lock_update

### ISSUE THREAD

**Issue by nickdevore** [JoshuaMulliken/ha-wyzeapi#340]
Wyze Integration: v0.1.4
HACS: 1.22.0

I'm getting the following exception

```
Logger: homeassistant.util.logging
Source: util/logging.py:105
First occurred: February 7, 2022, 8:36:32 AM (8166 occurrences)
Last logged: February 7, 2022, 10:29:05 PM

Exception in handle_lock_update when dispatching 'wyzeapi.lock_updated-YD.LO1.3c5dc9fb64d8d856758bebc3721e1d73': (<Device: DeviceTypes.LOCK, YD.LO1.3c5dc9fb64d8d856758bebc3721e1d73>,) Traceback (most recent call last): File "/config/custom_components/wyzeapi/sensor.py", line 86, in handle_lock_update if self.enabled is False | self.enabled is None: TypeError: unsupported operand type(s) for |: 'bool' and 'NoneType'
Exception in handle_lock_update when dispatching 'wyzeapi.lock_updated-YD.LO1.1c44bab7222c548cac523b6fbcbf182b': (<Device: DeviceTypes.LOCK, YD.LO1.1c44bab7222c548cac523b6fbcbf182b>,) Traceback (most recent call last): File "/config/custom_components/wyzeapi/sensor.py", line 86, in handle_lock_update if self.enabled is False | self.enabled is None: TypeError: unsupported operand type(s) for |: 'bool' and 'NoneType'
```

I'll take a look under the covers and see if I can't resolve that one.  Or is this potentially related to something else?

**Comment by nickdevore** [comment]
Never mind.  This was fixed with #334
