### ISSUE TITLE
[Bug] Switches stop working and/or fail to update status

### ISSUE THREAD

**Issue by b0rrasca** [JoshuaMulliken/ha-wyzeapi#344]
**Describe the bug**
Switches stop working and/or fail to update status (e.g. shows light on when they are not and viceversa)

**To Reproduce**

Unclear how to reproduce this. Seems to happen at random. 

**Expected behavior**
Status should update, and toggles should work

**System configuration**
System: Home Assistant Core (Docker)
HA Version: 2022.2.6
WyzeApi Version: Unsure

**home-assistant.log**

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1648, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1667, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/config/custom_components/wyzeapi/token_manager.py", line 45, in inner_function
    await func(*args, **kwargs)
  File "/config/custom_components/wyzeapi/switch.py", line 181, in async_turn_off
    await self._service.turn_off(self._device)
  File "/usr/local/lib/python3.9/site-packages/wyzeapy/services/switch_service.py", line 46, in turn_off
    await self._set_property(switch, PropertyIDs.ON.value, "0")
  File "/usr/local/lib/python3.9/site-packages/wyzeapy/services/base_service.py", line 335, in _set_property
    await self._auth_lib.refresh_if_should()
  File "/usr/local/lib/python3.9/site-packages/wyzeapy/wyze_auth_lib.py", line 178, in refresh_if_should
    await self.refresh()
  File "/usr/local/lib/python3.9/site-packages/wyzeapy/wyze_auth_lib.py", line 200, in refresh
    response_json = await response.json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1098, in json
    await self.read()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1036, in read
    self._body = await self.content.read()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 375, in read
    block = await self.readany()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 397, in readany
    await self._wait("readany")
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 304, in _wait
    await waiter
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

**Comment by yoinx** [comment]
Just a guess... But since aiohttp is the root with "None" when it was expecting body content. I'm guessing that either their API is having connection issues, or your internet might be?

Has this been an ongoing problem, or something that just randomly started without associated updates of anything?

**Comment by b0rrasca** [comment]
> Just a guess... But since aiohttp is the root with "None" when it was expecting body content. I'm guessing that either their API is having connection issues, or your internet might be?
> 
> Has this been an ongoing problem, or something that just randomly started without associated updates of anything?

Thank you. I have only been using [ha-wyzeapi](https://github.com/JoshuaMulliken/ha-wyzeapi) for about a week or so, so I have not had enough time to evaluate what may be causing this. I doubt It's due to connection issues, as the integration I use through homebridge ([homebridge-wyze-connected-home-v3](https://github.com/amrishraje/homebridge-wyze-connected-home-v3)) works without issue

**Comment by yoinx** [comment]
You're using both at the same time and you're not hitting their polling limits?

**Comment by b0rrasca** [comment]
I am mainly relying on the homebridge integration through my phone. I use the home assistant integration through my dashboard, which I rely on much less than my phone. Having said that, maybe the issue with Hass is due to reaching those polling limits? Wouldn't that also cause issues in homebridge, though?

**Comment by yoinx** [comment]
It should, yes. But I really don't know since I don't use home bridge

**Comment by JoshuaMulliken** [comment]
Just published an update to fix this. There was a disconnect between wyzeapy and ha-wyzeapi
