### ISSUE TITLE
[Bug] Notifications Switch not working.

### ISSUE THREAD

**Issue by sambarlick** [JoshuaMulliken/ha-wyzeapi#359]
**Describe the bug**
The Notifications toggle in the Wyze intergration not working.

See screenshot of error message and logs below.

I'm on v.0.17 of the intergration and 2022.3.4 of HA.
I downgraded to v.0.15 of the intergration to test but still had the error.

Sam

**home-assistant.log**

```
2022-03-15 17:06:56 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548208111520] Cannot connect to host apiq.wyzecam.com:443 ssl:default [Name does not resolve]
File "/config/custom_components/wyzeapi/switch.py", line 95, in async_turn_off
File "/usr/local/lib/python3.9/site-packages/wyzeapy/__init__.py", line 162, in disable_notifications
File "/usr/local/lib/python3.9/site-packages/wyzeapy/services/base_service.py", line 74, in set_push_info
File "/usr/local/lib/python3.9/site-packages/wyzeapy/wyze_auth_lib.py", line 219, in post
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host apiq.wyzecam.com:443 ssl:default [Name does not resolve]

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/wyzeapi/switch.py:95
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 5:06:56 PM (1 occurrences)
Last logged: 5:06:56 PM

[548208111520] Cannot connect to host apiq.wyzecam.com:443 ssl:default [Name does not resolve]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 192, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1636, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1673, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 949, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/config/custom_components/wyzeapi/switch.py", line 95, in async_turn_off
    await self._client.disable_notifications()
  File "/usr/local/lib/python3.9/site-packages/wyzeapy/__init__.py", line 162, in disable_notifications
    await self._service.set_push_info(False)
  File "/usr/local/lib/python3.9/site-packages/wyzeapy/services/base_service.py", line 74, in set_push_info
    response_json = await self._auth_lib.post(url, json=payload)
  File "/usr/local/lib/python3.9/site-packages/wyzeapy/wyze_auth_lib.py", line 219, in post
    response = await _session.post(url, json=json, headers=headers, data=data)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host apiq.wyzecam.com:443 ssl:default [Name does not resolve]

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:601
First occurred: 5:04:38 PM (2 occurrences)
Last logged: 5:04:38 PM

Entity siren.lounge_cam_siren (<class 'custom_components.wyzeapi.siren.WyzeCameraSiren'>) implements device_state_attributes. Please report it to the custom component author.
Entity siren.bedroom_cam_siren (<class 'custom_components.wyzeapi.siren.WyzeCameraSiren'>) implements device_state_attributes. Please report it to the custom component author.

![Screenshot_20220315-172133](https://user-images.githubusercontent.com/47462284/158319895-0b74d45b-ef97-43a1-947a-e05a90e6a285.png)

```

**Comment by yoinx** [comment]
Cannot connect to host apiq.wyzecam.com:443 ssl:default [Name does not resolve]

And your internet is working fine?

**Comment by yoinx** [comment]
I'm curious how you're hitting that apiq.wyzecam.com address.

https://github.com/JoshuaMulliken/wyzeapy/blob/b3ff47e0cdf2b3c66ede6bc32eae6bbec1f5dc98/src/wyzeapy/services/base_service.py#L54


This is the function that ultimately gets called. The address that your log shows ... Is not the address is trying to access.

**Comment by sambarlick** [comment]
> This is the function that ultimately gets called. The address that your log shows ... Is not the address is trying to access.

I haven't changed anything, I've even removed the intergration done a fresh install.

**Comment by nicosaurus** [comment]
I get the same issue with the same log results. My internet is working fine and I have not changed anything in HA or wyze.

**Comment by JoshuaMulliken** [comment]
This is so weird `apiq.wyzecam.com` does not exist in the code...

This is where the exception is taking place:

```python
url = "https://api.wyzecam.com/app/user/set_push_info"
payload = {
    "phone_system_type": PHONE_SYSTEM_TYPE,
    "app_version": APP_VERSION,
    "app_ver": APP_VER,
    "push_switch": "1" if on else "2",
    "sc": SC,
    "ts": int(time.time()),
    "sv": SV,
    "access_token": self._auth_lib.token.access_token,
    "phone_id": PHONE_ID,
    "app_name": APP_NAME
}

response_json = await self._auth_lib.post(url, json=payload)
```

Something is definitely wrong with your install.

**Comment by nicosaurus** [comment]
Today's update to 0.1.8 has fixed this issue for me. The notification toggle now works properly again.

**Comment by JoshuaMulliken** [comment]
Great!

**Comment by sambarlick** [comment]
Fixed for me as well. Thanks.
