### ISSUE TITLE
[Bug] Wyze Climate not loading

### ISSUE THREAD

**Issue by r14n** [JoshuaMulliken/ha-wyzeapi#386]
**Describe the bug**
Climate never works, the rest of my wyze devices do.  It doesn't load, there is no climate entity, no info available.

**To Reproduce**
Load home assistant

**Expected behavior**

**System configuration**
System: VirtualBox on MacOS
Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1
Kernel version 5.15.41
Agent version 1.2.1

**home-assistant.log**

```
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
2022-05-28 10:40:40 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2022-05-28 10:40:40 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2022-05-28 11:34:55 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2022-05-28 12:30:50 ERROR (Recorder) [homeassistant] Error doing job: Unclosed connection
2022-05-28 12:42:49 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2022-05-28 12:42:49 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2022-05-28 12:49:02 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2022-05-28 12:49:02 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2022-05-28 13:06:24 WARNING (MainThread) [homeassistant.components.vizio.media_player] Lost connection to 192.168.100.2:7345
2022-05-28 13:06:26 ERROR (MainThread) [homeassistant.components.alexa.smart_home] Uncaught exception processing Alexa Alexa.Speaker/AdjustVolume request (media_player.tv)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/alexa/smart_home.py", line 41, in async_handle_message
    response = await funct_ref(hass, config, directive, context)
  File "/usr/src/homeassistant/homeassistant/components/alexa/handlers.py", line 526, in async_api_adjust_volume
    current = math.floor(int(current_level * 100))
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
2022-05-28 13:27:32 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2022-05-28 14:11:11 ERROR (MainThread) [homeassistant.components.hassio] The system cannot restart because the configuration is not valid: Invalid config for [logger]: expected a dictionary for dictionary value @ data['logger']['logs']. Got None
extra keys not allowed @ data['logger']['custom_components.wyzeapi']. Got 'debug'. (See /config/configuration.yaml, line 17). 
2022-05-28 14:11:11 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139668074445024] The system cannot restart because the configuration is not valid: Invalid config for [logger]: expected a dictionary for dictionary value @ data['logger']['logs']. Got None
extra keys not allowed @ data['logger']['custom_components.wyzeapi']. Got 'debug'. (See /config/configuration.yaml, line 17). 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 189, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 679, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Invalid config for [logger]: expected a dictionary for dictionary value @ data['logger']['logs']. Got None
extra keys not allowed @ data['logger']['custom_components.wyzeapi']. Got 'debug'. (See /config/configuration.yaml, line 17). 
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
2022-05-28 14:12:44 ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /homeassistant/restart request Server disconnected
Found 2 non-daemonic threads.
[finish] process exit code 0
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2022-05-28 14:13:03 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration wyzeapi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-28 14:13:03 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-28 14:13:03 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration ui_lovelace_minimalist which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-28 14:13:03 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration multizone_controller which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-28 14:13:03 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-28 14:13:09 DEBUG (MainThread) [custom_components.wyzeapi] Nothing to import from configuration.yaml, loading from Integrations
2022-05-28 14:13:15 WARNING (MainThread) [homeassistant.config_entries] Config entry 'HL-3180CDW U64163F7J240689' for brother integration not ready yet: Bad IPv4/UDP transport address BRWD80F994D4E0E.local@161: [Errno -3] Try againcaused by <class 'socket.gaierror'>: [Errno -3] Try again; Retrying in background
2022-05-28 14:13:15 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139905676941584] Received invalid command: hacs/subscribe
2022-05-28 14:13:15 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139905676941584] Received invalid command: hacs/subscribe
2022-05-28 14:13:15 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139905676941584] Received invalid command: hacs/subscribe
2022-05-28 14:13:15 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139905676941584] Received invalid command: hacs/subscribe
2022-05-28 14:13:15 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139905676941584] Received invalid command: hacs/subscribe
2022-05-28 14:13:15 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139905676941584] Received invalid command: hacs/subscribe
2022-05-28 14:13:15 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139905676941584] Received invalid command: hacs/subscribe
2022-05-28 14:13:15 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139905676941584] Received invalid command: hacs/subscribe
2022-05-28 14:13:17 DEBUG (MainThread) [custom_components.wyzeapi.sensor] Creating new WyzeApi sensor component
2022-05-28 14:13:17 DEBUG (MainThread) [custom_components.wyzeapi.switch] Creating new WyzeApi light component
2022-05-28 14:13:17 DEBUG (MainThread) [custom_components.wyzeapi.lock] Creating new WyzeApi lock component
2022-05-28 14:13:17 DEBUG (MainThread) [custom_components.wyzeapi.climate] Creating new WyzeApi thermostat component
2022-05-28 14:13:17 DEBUG (MainThread) [custom_components.wyzeapi.alarm_control_panel] Creating new WyzeApi Home Monitoring System component
2022-05-28 14:13:17 DEBUG (MainThread) [custom_components.wyzeapi.siren] Creating new WyzeApi siren component
2022-05-28 14:13:17 DEBUG (MainThread) [custom_components.wyzeapi.light] Creating new WyzeApi light component
2022-05-28 14:13:18 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Brother HL-3180CDW' for ipp integration not ready yet: Invalid response from API: Timeout occurred while connecting to IPP server.; Retrying in background
2022-05-28 14:13:27 WARNING (MainThread) [homeassistant.components.climate] Setup of climate platform wyzeapi is taking over 10 seconds.
2022-05-28 14:14:08 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: climate.wyzeapi
2022-05-28 14:14:17 ERROR (MainThread) [homeassistant.components.climate] wyzeapi: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in async_device_update
    await task
  File "/config/custom_components/wyzeapi/token_manager.py", line 45, in inner_function
    await func(*args, **kwargs)
  File "/config/custom_components/wyzeapi/climate.py", line 306, in async_update
    self._thermostat = await self._thermostat_service.update(self._thermostat)
  File "/usr/local/lib/python3.9/site-packages/wyzeapy/services/thermostat_service.py", line 62, in update
    properties = (await self._thermostat_get_iot_prop(thermostat))['data']['props']
  File "/usr/local/lib/python3.9/site-packages/wyzeapy/services/base_service.py", line 557, in _thermostat_get_iot_prop
    response_json = await self._auth_lib.get(url, headers=headers, params=payload)
  File "/usr/local/lib/python3.9/site-packages/wyzeapy/wyze_auth_lib.py", line 236, in get
    response = await _session.get(url, params=params, headers=headers)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
2022-05-28 14:14:25 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection

```

**Comment by JoshuaMulliken** [comment]
@r14n Looks like the Wyze Server disconnected. Does a restart change anything? There is not much we can do if their servers are not working.

**Comment by r14n** [comment]
Restarting HA does nothing.  Restarting the thermostat didn't work either.

**Comment by febbins** [comment]
The temperature is not showing correctly. Please advise. Thanks

![image](https://user-images.githubusercontent.com/106814913/172093100-151ec1ec-d754-4bff-8e05-8aebc144e508.png)
![C](https://user-images.githubusercontent.com/106814913/172093125-f17facfc-b2fa-4557-91d3-686c6f387b98.png)

**Comment by r14n** [comment]
> The temperature is not showing correctly. Please advise. Thanks
> 
Is this a Wyze thermostat you're using?

**Comment by JoshuaMulliken** [comment]
@r14n do you have an update on your issue? Should this item be closed?

**Comment by r14n** [comment]
Not sure why it's working when it wasn't before, but it is.

**Comment by febbins** [comment]
Yes, I am using wyze.
