### ISSUE TITLE
[Bug] Unable  to log in

### ISSUE THREAD

**Issue by iainsmacleod** [JoshuaMulliken/ha-wyzeapi#401]
**Describe the bug**
Unable to log in

**To Reproduce**
1. Add Wyze integration
2. After entering credentials (and not being asked for 2FA)
3. See error

**Expected behavior**
Presented with 2FA and logged in

**System configuration**
System: VM
Home Assistant 2022.8.4
Supervisor 2022.08.3
Operating System 8.4
Frontend 20220802.0 - latest

**home-assistant.log**

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 277, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/wyzeapi/config_flow.py", line 59, in async_step_user
    await self.client.login(
  File "/usr/local/lib/python3.10/site-packages/wyzeapy/__init__.py", line 79, in login
    await self._auth_lib.get_token_with_username_password(email, password)
  File "/usr/local/lib/python3.10/site-packages/wyzeapy/wyze_auth_lib.py", line 109, in get_token_with_username_password
    raise UnknownApiError(response_json)
wyzeapy.exceptions.UnknownApiError: {'description': 'Internal Error', 'requestId': '***removed****', 'errorCode': 5000}

**Comment by iainsmacleod** [comment]
Seems I needed email and not username, even though it said username. I'm good now.

**Comment by frakman1** [comment]
I just ran into this issue too.

@JoshuaMulliken  Can you please fix the login field to ask for "email" instead of "username"?

![image](https://user-images.githubusercontent.com/5826484/212439789-8808fba6-ef7d-4220-8e04-cb65967d5c59.png)
