### ISSUE TITLE
[Bug] Not all cameras support motion detection switches

### ISSUE THREAD

**Issue by JoeSchubert** [JoshuaMulliken/ha-wyzeapi#442]
**Describe the bug**
This commit https://github.com/JoshuaMulliken/ha-wyzeapi/commit/4f0060b764363a2c36953767b330042e5a1e408d added a motion detection switch to all cameras. However, not all cameras support this. In my instance, everytime that my Doorbell Camera (model GW_BE1) is polled I get the following error: 

I believe that this should likely have a guard clause at line 66 https://github.com/JoshuaMulliken/ha-wyzeapi/blob/4f0060b764363a2c36953767b330042e5a1e408d/custom_components/wyzeapi/switch.py#L66 to prevent adding the motion switch for models that do not support it.

**To Reproduce**

1. Have a doorbell cam
2. Let the integration poll the cameras

**Expected behavior**
The integration should not throw an error.

**System configuration**
System: Hass Os in  VM on Proxmox
HA Version: Home Assistant 2023.2.0.dev0
WyzeApi Version: 0.1.16

**home-assistant.log**
2023-01-06 20:28:18.114 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_camera_update when dispatching 'wyzeapi.camera_updated-GW_BE1_7C78B2A22294': (<Device: DeviceTypes.CAMERA, GW_BE1_7C78B2A22294>,)
Traceback (most recent call last):
  File "/workspaces/core/config/custom_components/wyzeapi/switch.py", line 454, in handle_camera_update
    self.async_write_ha_state()
  File "/workspaces/core/homeassistant/helpers/entity.py", line 556, in async_write_ha_state
    self._async_write_ha_state()
  File "/workspaces/core/homeassistant/helpers/entity.py", line 597, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/workspaces/core/homeassistant/helpers/entity.py", line 562, in _stringify_state
    if (state := self.state) is None:
  File "/workspaces/core/homeassistant/helpers/entity.py", line 997, in state
    if (is_on := self.is_on) is None:
  File "/workspaces/core/config/custom_components/wyzeapi/switch.py", line 443, in is_on
    return self._device.motion
AttributeError: 'Camera' object has no attribute 'motion'

Tagging @brg468  as this was added by them.

**Comment by brg468** [comment]
Oh man I didn’t think of that, I don’t have anything else with cameras. I’ll get a fix together when I get a minute.

**Comment by JoeSchubert** [comment]
no worries. I'm working on one right now as well since I'm getting the error. I just wanted to make sure to open an issue to track the error. I'm about to open another issue because 2fa is broken now for some reason as well.

I'm not sure if it's better to list models that support/don't support motion in Wyzeapy and check against that as a boolean. Or do to it in the integration though.

**Comment by JoeSchubert** [comment]
@brg468 Please see the PR above that references this issue. I don't know if this is cleaner than creating a boolean in Wyzeapy to check against or just handling it here.

**Comment by brg468** [comment]
This way is probably the easiest, and seems to stick with the convention of leaving the determination whether or not to add entities to the ha side of things. Thanks for taking care of that!
