### ISSUE TITLE
[Bug] Not receiving 2-factor authentication code

### ISSUE THREAD

**Issue by GregSloan** [JoshuaMulliken/ha-wyzeapi#448]
**Describe the bug**
I'm attempting to log in for the first time. I know I'm successfully authenticating with email and password because if I type the wrong password I get a different error. But when I get my password right, I get the "Enter Wyze 2FA Verification Code" prompt, however I never receive the code. When I login on the Wyze app or website, I do get the 2FA code. 

**To Reproduce**

1. Go to Settings
2. Go to "Devices & Sercices"
3. click "+ Add Integration"
4. Search for Wyze
5. Enter Username and Password

**Expected behavior**
I should receive a text with my 2FA Verification code

**System configuration**
System: Home Assistant Docker  
HA Version: 2023.1.2
WyzeApi Version: 0.1.16

**home-assistant.log**
Here is the log - but NOTE - I don't see ANY logs when I get my username and password correct. The exceptions that show in the log are only when I get my username and password incorrect.

2023-01-13 11:51:53 [11:51:53] INFO: Home Assistant Core finish process exit code 0
2023-01-13 11:51:53 [11:51:53] INFO: Home Assistant Core service shutdown
2023-01-13 11:51:53 s6-rc: info: service legacy-services successfully stopped
2023-01-13 11:51:53 s6-rc: info: service legacy-cont-init: stopping
2023-01-13 11:51:53 s6-rc: info: service legacy-cont-init successfully stopped
2023-01-13 11:51:53 s6-rc: info: service fix-attrs: stopping
2023-01-13 11:51:53 s6-rc: info: service fix-attrs successfully stopped
2023-01-13 11:51:53 s6-rc: info: service s6rc-oneshot-runner: stopping
2023-01-13 11:51:53 s6-rc: info: service s6rc-oneshot-runner successfully stopped
2023-01-13 11:51:57 s6-rc: info: service s6rc-oneshot-runner: starting
2023-01-13 11:51:57 s6-rc: info: service s6rc-oneshot-runner successfully started
2023-01-13 11:51:57 s6-rc: info: service fix-attrs: starting
2023-01-13 11:51:57 s6-rc: info: service fix-attrs successfully started
2023-01-13 11:51:57 s6-rc: info: service legacy-cont-init: starting
2023-01-13 11:51:57 s6-rc: info: service legacy-cont-init successfully started
2023-01-13 11:51:57 s6-rc: info: service legacy-services: starting
2023-01-13 11:51:57 services-up: info: copying legacy longrun home-assistant (no readiness notification)
2023-01-13 11:51:57 s6-rc: info: service legacy-services successfully started
2023-01-13 11:51:59 2023-01-13 11:51:59.800 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-13 11:51:59 2023-01-13 11:51:59.809 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration wyzeapi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-13 11:52:41 2023-01-13 11:52:41.976 ERROR (MainThread) [wyzeapy.wyze_auth_lib] Unable to login with response from Wyze: {'description': 'Invalid User Name or Password.', 'requestId': '133c841e-2f65-4589-ad8e-066d239272d3', 'errorCode': 1000}
2023-01-13 11:52:42 2023-01-13 11:52:41.998 ERROR (MainThread) [aiohttp.server] Error handling request
2023-01-13 11:52:42 Traceback (most recent call last):
2023-01-13 11:52:42   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
2023-01-13 11:52:42     resp = await request_handler(request)
2023-01-13 11:52:42   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
2023-01-13 11:52:42     resp = await handler(request)
2023-01-13 11:52:42   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
2023-01-13 11:52:42     return await handler(request)
2023-01-13 11:52:42   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
2023-01-13 11:52:42     return await handler(request)
2023-01-13 11:52:42   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
2023-01-13 11:52:42     return await handler(request)
2023-01-13 11:52:42   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
2023-01-13 11:52:42     return await handler(request)
2023-01-13 11:52:42   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
2023-01-13 11:52:42     return await handler(request)
2023-01-13 11:52:42   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
2023-01-13 11:52:42     return await handler(request)
2023-01-13 11:52:42   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
2023-01-13 11:52:42     result = await result
2023-01-13 11:52:42   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
2023-01-13 11:52:42     return await super().post(request, flow_id)
2023-01-13 11:52:42   File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
2023-01-13 11:52:42     result = await method(view, request, data, *args, **kwargs)
2023-01-13 11:52:42   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
2023-01-13 11:52:42     result = await self._flow_mgr.async_configure(flow_id, data)
2023-01-13 11:52:42   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 286, in async_configure
2023-01-13 11:52:42     result = await self._async_handle_step(
2023-01-13 11:52:42   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 374, in _async_handle_step
2023-01-13 11:52:42     result: FlowResult = await getattr(flow, method)(user_input)
2023-01-13 11:52:42   File "/config/custom_components/wyzeapi/config_flow.py", line 59, in async_step_user
2023-01-13 11:52:42     await self.client.login(
2023-01-13 11:52:42   File "/usr/local/lib/python3.10/site-packages/wyzeapy/__init__.py", line 81, in login
2023-01-13 11:52:42     await self._auth_lib.get_token_with_username_password(email, password)
2023-01-13 11:52:42   File "/usr/local/lib/python3.10/site-packages/wyzeapy/wyze_auth_lib.py", line 109, in get_token_with_username_password
2023-01-13 11:52:42     raise UnknownApiError(response_json)
2023-01-13 11:52:42 wyzeapy.exceptions.UnknownApiError: {'description': 'Invalid User Name or Password.', 'requestId': '133c841e-2f65-4589-ad8e-066d239272d3', 'errorCode': 1000}

**Comment by JoeSchubert** [comment]
I ran into this as well recently, and it's got to do with some design choices I made when implementing the 2FA support.

If you have both SMS and TOTP enabled, you'll never get the SMS code. You'll have to use the TOTP code to log in.

**Comment by GregSloan** [comment]
Aha! That was it. Deleted all but sms from 2FA methods and it worked. Thanks for the quick response!
