### ISSUE TITLE
Unable to get wyzeapi setup[Bug]

### ISSUE THREAD

**Issue by johnfuller5** [JoshuaMulliken/ha-wyzeapi#57]
**Describe the bug**
Error on setup of wyzeapi

**To Reproduce**
1. Install repository from HACS
2. Edit configuration.yaml file and save
3. restart HASS
4. Notification of error: Invalid config  The following integrations and platforms could not be set up: wyzeapi  Please check your config.

**Expected behavior**
Install and setup of wyzeapi - discovery of switches and lights

**System configuration**
System: Windows 10
HA Version: 0.110.2
WyzeApi Version: 0.4.2

**configuration.yaml**

```yaml
wyzeapi:
  username: myusername
  password: mypassword
```

**home-assistant.log**

```
Log Details (ERROR)
Logger: homeassistant.setup
Source: c:\users\johnf_000\appdata\local\programs\python\python38\lib\site-packages\homeassistant\setup.py:181
First occurred: 12:57:46 PM (1 occurrences)
Last logged: 12:57:46 PM

Error during setup of component wyzeapi
Traceback (most recent call last):
  File "c:\users\johnf_000\appdata\local\programs\python\python38\lib\site-packages\homeassistant\setup.py", line 170, in _async_setup_component
    result = await component.async_setup(  # type: ignore
  File "C:\Users\johnf_000\AppData\Roaming\.homeassistant\custom_components\wyzeapi\__init__.py", line 46, in async_setup
    wyzeapi_devices = await wyzeapi_account.async_get_devices()
  File "C:\Users\johnf_000\AppData\Roaming\.homeassistant\custom_components\wyzeapi\wyzeapi\wyzeapi.py", line 69, in async_get_devices
    "ts": datetime.datetime.now().strftime("%s"),
ValueError: Invalid format string
```

**Comment by jfarmer08** [comment]
This could just be an windows issues. I have only tested on Linux.

**Comment by JoshuaMulliken** [comment]
I haven't seen this either

**Comment by int-rnd** [comment]
I am also having this problem. Running on linux (raspberry pi). error:

`2020-06-04 23:48:02 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for wyzeapi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-04 23:48:02 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-04 23:48:02 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for blueiris which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-04 23:48:20 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform wyzeapi.light: Platform not found (cannot import name 'LightEntity' from 'homeassistant.components.light' (/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/light/__init__.py)).
2020-06-04 23:48:24 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform wyzeapi.switch: Platform not found (cannot import name 'SwitchEntity' from 'homeassistant.components.switch' (/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/switch/__init__.py)).
2020-06-04 23:48:48 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform wyzeapi.binary_sensor: Platform not found (cannot import name 'BinarySensorEntity' from 'homeassistant.components.binary_sensor' (/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/binary_sensor/__init__.py)).
2020-06-04 23:48:48 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform wyzeapi.lock: Platform not found (cannot import name 'LockEntity' from 'homeassistant.components.lock' (/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/lock/__init__.py)).
`

**Comment by jfarmer08** [comment]
What Version of Home Assistant are you using and what version of WyzeAPi are you using?

**Comment by Corradiac** [comment]
@int-rnd it runs fine on the latest version of HA. 

I was having the similar issue as yours.  'Platform not found' for my wyze lock, until I updated HA from 0.109.6 to 0.110.5 (latest).

**Comment by jfarmer08** [comment]
@int-rnd  Are you still having an issue if you upgrade HA

**Comment by diegotv** [comment]
Yup

Just upgraded to Home Assistant 0.111.0
Still getting the notification: 

> 
> **Invalid config**
> The following integrations and platforms could not be set up:
> 
> Wyzeapi
> Please check your config.
> 

And this is from log:

> Logger: homeassistant.setup
> Source: custom_components/wyzeapi/wyzeapi/wyze_request.py:51
> First occurred: 12:13:06 PM (1 occurrences)
> Last logged: 12:13:06 PM
> 
> Error during setup of component wyzeapi
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 190, in _async_setup_component
>     result = await asyncio.wait_for(task, SLOW_SETUP_MAX_WAIT)
>   File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
>     return fut.result()
>   File "/config/custom_components/wyzeapi/__init__.py", line 48, in async_setup
>     await wyzeapi_account.async_init()
>   File "/config/custom_components/wyzeapi/wyzeapi/wyzeapi.py", line 33, in async_init
>     await self.async_login()
>   File "/config/custom_components/wyzeapi/wyzeapi/wyzeapi.py", line 58, in async_login
>     data = await self.async_do_request(url, payload)
>   File "/config/custom_components/wyzeapi/wyzeapi/wyzeapi.py", line 204, in async_do_request
>     return await WyzeRequest(url, payload).async_get_response()
>   File "/config/custom_components/wyzeapi/wyzeapi/wyze_request.py", line 51, in async_get_response
>     raise WyzeApiError("Payload: " + str(self._payload) + "\nResponse Data: " + str(data))
> custom_components.wyzeapi.wyzeapi.wyzeapi_exceptions.WyzeApiError: Payload: {"phone_id": "bc151f39-787b-4871-be27-5a20fd0a1937", "app_name": "com.hualai.WyzeCam", "app_version": "2.6.62", "sc": "9f275790cab94a72bd206c8876429f3c", "password": "XXX", "sv": "41267de22d1847c8b99bfba2658f88d7", "user_name": "XXX", "two_factor_auth": "", "phone_system_type": "1", "app_ver": "com.hualai.WyzeCam___2.6.62", "ts": "1575955440030", "access_token": ""}
> Response Data: {'ts': 1591816385239, 'code': '3033', 'msg': 'UserOpenTwoFactorAuth', 'data': {}}

**Comment by jfarmer08** [comment]
@diegotv You have MFA(Muti Factor Authentication) Wyze calls it Two Factor Authentication turned on. The last line in the log is the give away. As stated in the Readme WyzeAPI does not support Two Factor Authentication at this time. We hope support this in the feature release.

Response Data: {'ts': 1591816385239, 'code': '3033', 'msg': 'UserOpenTwoFactorAuth', 'data': {}}

**Comment by diegotv** [comment]
Jeez

I didn't realize I had it on 
Everything was just seen

Thank you

**Comment by jfarmer08** [comment]
Glad it’s working. We can close this.
