### ISSUE TITLE
WyzeApi failure when calling lock.lock service using lock.front_door device

### ISSUE THREAD

**Issue by terrycarlin** [JoshuaMulliken/ha-wyzeapi#63]
**Describe the bug**

**To Reproduce**
1. Go to 'Developer Tools'
2. Click on 'Services.'
3. Enter lock.lock for Service
4. Enter lock.front_door for Service Data
5. Press Call Service
6. Lock does not lock
7. See error in home-assistant.log

This error comes up using Service lock.unlock also.

When locking and unlocking the front_door lock normally via the Wyze app or automatic lock and unlock features, or manually locking and.unlocking, the lock status is reported correctly.

**Expected behavior**

The lock should lock or unlock and the state should reflect the change.
**System configuration**
System: 
HA Version: 
WyzeApi Version:  

**configuration.yaml**

```yaml
wyzeapi:
  username: !secret wyze_userid
  password: !secret wyze_password
```

**home-assistant.log**

```
2020-06-20 10:45:46 DEBUG (MainThread) [custom_components.wyzeapi.lock] Binary Locks doing a update.
2020-06-20 10:45:46 DEBUG (MainThread) [custom_components.wyzeapi.wyzeapi.wyze_lock] Lock Front Door updating.
2020-06-20 10:45:46 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/wyzeapi/wyzeapi/wyzeapi.py", line 205, in async_do_request
    return await WyzeRequest(url, payload).async_get_response()
  File "/home/homeassistant/.homeassistant/custom_components/wyzeapi/wyzeapi/wyze_request.py", line 45, in async_get_response
    data = await resp.json()
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/client_reqrep.py", line 1031, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=us-ascii', url='https://beta-api.wyzecam.com/app/v2/auto/run_action
```

Edit: I found that this exception came from getting a 404 status from 
url: https://beta-api.wyzecam.com/app/v2/auto/run_action

**Comment by jfarmer08** [comment]
@terrycarlin  This is clearly stated in the Readme that Lock and Unlock is not supported.. 

[https://github.com/JoshuaMulliken/ha-wyzeapi/blob/master/README.md](https://github.com/JoshuaMulliken/ha-wyzeapi/blob/master/README.md)

View Wyze Lock Status and Door Status as lock through HA
Note: Currently you can only view the lock status or door status. Lock and Unlock does not work!
