### ISSUE TITLE
Error during setup of component wyzeapi

### ISSUE THREAD

**Issue by Kilonga** [JoshuaMulliken/ha-wyzeapi#65]
I manually installed the wyzeapi because I was getting an error when doing it through the UI.  After entering the credentials in the configuration.yaml file I am getting the following error:

```
Error during setup of component wyzeapi

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 193, in _async_setup_component
    result = await asyncio.wait_for(task, SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/wyzeapi/__init__.py", line 48, in async_setup
    await wyzeapi_account.async_init()
  File "/config/custom_components/wyzeapi/wyzeapi/wyzeapi.py", line 33, in async_init
    await self.async_login()
  File "/config/custom_components/wyzeapi/wyzeapi/wyzeapi.py", line 58, in async_login
    data = await self.async_do_request(url, payload)
  File "/config/custom_components/wyzeapi/wyzeapi/wyzeapi.py", line 204, in async_do_request
    return await WyzeRequest(url, payload).async_get_response()
  File "/config/custom_components/wyzeapi/wyzeapi/wyze_request.py", line 51, in async_get_response
    raise WyzeApiError("Payload: " + str(self._payload) + "\nResponse Data: " + str(data))
custom_components.wyzeapi.wyzeapi.wyzeapi_exceptions.WyzeApiError: Payload: {"phone_id": "bc151f39-787b-XXXX-XXXX-5a20fd0a1937", "app_name": "com.hualai.WyzeCam", "app_version": "2.6.62", "sc": "9f275790cab94a72bd206c8876429f3c", "password": "XXXXXXXXXX", "sv": "41267de22d1847c8b99bfba2658f88d7", "user_name": "carlosi@iadb.org", "two_factor_auth": "", "phone_system_type": "1", "app_ver": "com.hualai.WyzeCam___2.6.62", "ts": "1575955440030", "access_token": ""}
Response Data: {'ts': 1594143264947, 'code': '2000', 'msg': 'UserNameOrPasswordError', 'data': {}}
```
Any ideas?

**Comment by JoshuaMulliken** [comment]
It looks like the password is incorrect.

**Comment by JoshuaMulliken** [comment]
Do you have two factor enabled?

**Comment by jfarmer08** [comment]
yeah there is an issue with the username or the password.  It looks like 2fa is turned off.

**Comment by Kilonga** [comment]
2FA is turned off and the username/password is correct.  I do have special character on my password.  Could that be the issue?

**Comment by JoshuaMulliken** [comment]
That shouldn't be a problem. If it is reporting the same error then that means that the Wyze servers believe that your password is wrong

**Comment by Kilonga** [comment]
I changed the password and it worked.  When including special characters such as # in the password it doesn't work, even when the character is 'escaped' in the configuratiom.yaml file.

**Comment by JoshuaMulliken** [comment]
Hmm, that is interesting. Thanks for the feedback
