### ISSUE TITLE
Keep getting  error 

### ISSUE THREAD

**Issue by onlinegill** [JoshuaMulliken/ha-wyzeapi#77]
Keep getting 

Log Details (ERROR)
Logger: homeassistant.components.binary_sensor
Source: custom_components/wyzeapi/wyzeapi/devices/base_sensor.py:27
Integration: Binary sensor (documentation, issues)
First occurred: 9:15:42 PM (2 occurrences)
Last logged: 9:15:42 PM

wyzeapi: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 335, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 454, in async_device_update
    await self.async_update()  # type: ignore
  File "/config/custom_components/wyzeapi/binary_sensor.py", line 206, in async_update
    await self.__client.update(self.__sensor)
  File "/config/custom_components/wyzeapi/wyzeapi/client.py", line 240, in update
    prop_map = device.prop_map()
  File "/config/custom_components/wyzeapi/wyzeapi/devices/base_sensor.py", line 27, in prop_map
    "P1302": self.open_close_state
AttributeError: 'MotionSensor' object has no attribute 'open_close_state'

**Comment by JoshuaMulliken** [comment]
Ok I just submitted a new release that should fix your problem! https://github.com/JoshuaMulliken/ha-wyzeapi/releases/tag/v0.5.3

**Comment by onlinegill** [comment]
> Ok I just submitted a new release that should fix your problem! https://github.com/JoshuaMulliken/ha-wyzeapi/releases/tag/v0.5.3
Thank you it working.
