### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by 1h8fulkat** [JoshuaMulliken/ha-wyzeapi#80]
**Describe the bug**
Upgraded the integration and now I can't control my switches.

**System configuration**
System: HASS OS
HA Version: 0.114.3
WyzeApi Version: v0.5.3

**home-assistant.log**

```
Log Details (ERROR)
Logger: homeassistant.components.switch
Source: custom_components/wyzeapi/wyzeapi/devices/switch.py:30
Integration: Switch (documentation, issues)
First occurred: 7:00:16 PM (2 occurrences)
Last logged: 7:00:16 PM

wyzeapi: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 335, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 454, in async_device_update
    await self.async_update()  # type: ignore
  File "/config/custom_components/wyzeapi/switch.py", line 106, in async_update
    await self.__client.update(self.__switch)
  File "/config/custom_components/wyzeapi/wyzeapi/client.py", line 238, in update
    prop_map = device.prop_map()
  File "/config/custom_components/wyzeapi/wyzeapi/devices/switch.py", line 30, in prop_map
    "P5": self.avaliable,
AttributeError: 'Switch' object has no attribute 'avaliable'
```

**Comment by hockey6611** [comment]
I have the same error. Seems to be related to #79 as well.

**Comment by 1h8fulkat** [comment]
This is a duplicate of Issue #79
